
server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: moto-service-route
          uri: lb://moto
          predicates:
            - Path=/motos/**
        - id: user-service-route
          uri: lb://users-microservice
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials





